// Follows from output_regressions.R
// Due to limits in Stata on the length of variable names, names differ from those created in R
// In addition, where names were identical after being shorted, they were replaced by "vXXX" names
//
// For example:
// winter_energy_payment_partnered_mother
// winter_energy_payment_partnered_father
//
// Where shortened to
// winter_energy_payment_partnered_
// winter_energy_payment_partnered_
//
// And as these are identical, the second one was renamed as v166, giving final names:
// winter_energy_payment_partnered_
// v166


clear

import delimited "I:\MAA2021-55\wellbeing report - tranche 2\Analysis\regression_dataset_for_stata.csv"

xtset snz_uid wave_num

/* fixed effects */
xtlogit good_health ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	mhs_qenoughincomeenough_money ///
	mhs_qenoughincomeonly_just_enoug ///
	mhs_qenoughincomenot_enough_mone ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	pwb_qtimelonelya_little_of_the_t ///
	pwb_qtimelonelysome_of_the_time ///
	pwb_qtimelonelymost_of_the_time ///
	pwb_qtimelonelyall_of_the_time ///
	hcq_qdampormouldminor_problem ///
	hcq_qdampormouldmajor_problem ///
	hcq_qkeepingwarmminor_problem ///
	hcq_qkeepingwarmmajor_problem ///
	any_benefit_receipt_winter_energ ///
	, fe
	

xtlogit not_lonely ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	mhs_qenoughincomeenough_money ///
	mhs_qenoughincomeonly_just_enoug ///
	mhs_qenoughincomenot_enough_mone ///
	pwb_qhealthexcellentpoorvery_goo ///
	pwb_qhealthexcellentpoorgood ///
	pwb_qhealthexcellentpoorfair ///
	pwb_qhealthexcellentpoorpoor ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	hcq_qdampormouldminor_problem ///
	hcq_qdampormouldmajor_problem ///
	hcq_qkeepingwarmminor_problem ///
	hcq_qkeepingwarmmajor_problem ///
	any_benefit_receipt_winter_energ ///
	, fe dif
	
xtlogit enough_income ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	pwb_qhealthexcellentpoorvery_goo ///
	pwb_qhealthexcellentpoorgood ///
	pwb_qhealthexcellentpoorfair ///
	pwb_qhealthexcellentpoorpoor ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	pwb_qtimelonelya_little_of_the_t ///
	pwb_qtimelonelysome_of_the_time ///
	pwb_qtimelonelymost_of_the_time ///
	pwb_qtimelonelyall_of_the_time ///
	hcq_qdampormouldminor_problem ///
	hcq_qdampormouldmajor_problem ///
	hcq_qkeepingwarmminor_problem ///
	hcq_qkeepingwarmmajor_problem ///
	any_benefit_receipt_winter_energ ///
	, fe
	
xtlogit no_damp_or_mould ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	mhs_qenoughincomeenough_money ///
	mhs_qenoughincomeonly_just_enoug ///
	mhs_qenoughincomenot_enough_mone ///
	pwb_qhealthexcellentpoorvery_goo ///
	pwb_qhealthexcellentpoorgood ///
	pwb_qhealthexcellentpoorfair ///
	pwb_qhealthexcellentpoorpoor ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	pwb_qtimelonelya_little_of_the_t ///
	pwb_qtimelonelysome_of_the_time ///
	pwb_qtimelonelymost_of_the_time ///
	pwb_qtimelonelyall_of_the_time ///
	hcq_qkeepingwarmminor_problem ///
	hcq_qkeepingwarmmajor_problem ///
	any_benefit_receipt_winter_energ ///
	, fe
	
xtlogit warm_home ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	mhs_qenoughincomeenough_money ///
	mhs_qenoughincomeonly_just_enoug ///
	mhs_qenoughincomenot_enough_mone ///
	pwb_qhealthexcellentpoorvery_goo ///
	pwb_qhealthexcellentpoorgood ///
	pwb_qhealthexcellentpoorfair ///
	pwb_qhealthexcellentpoorpoor ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	pwb_qtimelonelya_little_of_the_t ///
	pwb_qtimelonelysome_of_the_time ///
	pwb_qtimelonelymost_of_the_time ///
	pwb_qtimelonelyall_of_the_time ///
	hcq_qdampormouldminor_problem ///
	hcq_qdampormouldmajor_problem ///
	any_benefit_receipt_winter_energ ///
	, fe
	

/* random effects */
xtlogit good_health ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	mhs_qenoughincomeenough_money ///
	mhs_qenoughincomeonly_just_enoug ///
	mhs_qenoughincomenot_enough_mone ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	pwb_qtimelonelya_little_of_the_t ///
	pwb_qtimelonelysome_of_the_time ///
	pwb_qtimelonelymost_of_the_time ///
	pwb_qtimelonelyall_of_the_time ///
	hcq_qdampormouldminor_problem ///
	hcq_qdampormouldmajor_problem ///
	hcq_qkeepingwarmminor_problem ///
	hcq_qkeepingwarmmajor_problem ///
	any_benefit_receipt_winter_energ ///
	etheuropean ///
	ethmaori ///
	ethpacific ///
	ethasian ///
	ethmelaa ///
	ethother ///
	partnered_father_depchild ///
	partnered_mother_depchild ///
	solo_father_depchild ///
	solo_mother_depchild ///
	other_father ///
	other_mother ///
	youngest_child_agebaby_fm_pkg ///
	youngest_child_agebaby_no_pkg ///
	youngest_child_agetodler ///
	youngest_child_ageprimary ///
	youngest_child_ageintermediate ///
	youngest_child_agecollege ///
	low_income ///
	earned_self_emp ///
	age_cat20_to_29 ///
	age_cat30_to_39 ///
	age_cat40_to_49 ///
	age_cat50_to_59 ///
	age_cat60_to_69 ///
	age_cat70_to_79 ///
	age_cat80_up ///
	dvsexmale ///
	dvregcouncilbay_of_plenty ///
	dvregcouncilcanterbury ///
	dvregcouncilgisborne ///
	dvregcouncilhawkes_bay ///
	dvregcouncilmanawatu_wanganui ///
	dvregcouncilmarlborough ///
	dvregcouncilnelson ///
	dvregcouncilnorthland ///
	dvregcouncilotago ///
	dvregcouncilsouthland ///
	dvregcounciltaranaki ///
	dvregcounciltasman ///
	dvregcouncilwaikato ///
	dvregcouncilwellington ///
	dvregcouncilwest_coast ///
	winter_energy_payment_partnered_ ///
	v166 ///
	winter_energy_payment_solo_fathe ///
	winter_energy_payment_solo_mothe ///
	winter_energy_payment_low_income ///
	lockdown_any_partnered_father_de ///
	lockdown_any_partnered_mother_de ///
	lockdown_any_solo_father_depchil ///
	lockdown_any_solo_mother_depchil ///
	lockdown_any_youngest_child_ageb ///
	v175 ///
	lockdown_any_youngest_child_aget ///
	lockdown_any_youngest_child_agep ///
	lockdown_any_youngest_child_agei ///
	lockdown_any_youngest_child_agec ///
	any_benefit_receipt_partnered_fa ///
	any_benefit_receipt_partnered_mo ///
	any_benefit_receipt_solo_father_ ///
	any_benefit_receipt_solo_mother_ ///
	, re



xtlogit not_lonely ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	mhs_qenoughincomeenough_money ///
	mhs_qenoughincomeonly_just_enoug ///
	mhs_qenoughincomenot_enough_mone ///
	pwb_qhealthexcellentpoorvery_goo ///
	pwb_qhealthexcellentpoorgood ///
	pwb_qhealthexcellentpoorfair ///
	pwb_qhealthexcellentpoorpoor ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	hcq_qdampormouldminor_problem ///
	hcq_qdampormouldmajor_problem ///
	hcq_qkeepingwarmminor_problem ///
	hcq_qkeepingwarmmajor_problem ///
	any_benefit_receipt_winter_energ ///
	etheuropean ///
	ethmaori ///
	ethpacific ///
	ethasian ///
	ethmelaa ///
	ethother ///
	partnered_father_depchild ///
	partnered_mother_depchild ///
	solo_father_depchild ///
	solo_mother_depchild ///
	other_father ///
	other_mother ///
	youngest_child_agebaby_fm_pkg ///
	youngest_child_agebaby_no_pkg ///
	youngest_child_agetodler ///
	youngest_child_ageprimary ///
	youngest_child_ageintermediate ///
	youngest_child_agecollege ///
	low_income ///
	earned_self_emp ///
	age_cat20_to_29 ///
	age_cat30_to_39 ///
	age_cat40_to_49 ///
	age_cat50_to_59 ///
	age_cat60_to_69 ///
	age_cat70_to_79 ///
	age_cat80_up ///
	dvsexmale ///
	dvregcouncilbay_of_plenty ///
	dvregcouncilcanterbury ///
	dvregcouncilgisborne ///
	dvregcouncilhawkes_bay ///
	dvregcouncilmanawatu_wanganui ///
	dvregcouncilmarlborough ///
	dvregcouncilnelson ///
	dvregcouncilnorthland ///
	dvregcouncilotago ///
	dvregcouncilsouthland ///
	dvregcounciltaranaki ///
	dvregcounciltasman ///
	dvregcouncilwaikato ///
	dvregcouncilwellington ///
	dvregcouncilwest_coast ///
	winter_energy_payment_partnered_ ///
	v166 ///
	winter_energy_payment_solo_fathe ///
	winter_energy_payment_solo_mothe ///
	winter_energy_payment_low_income ///
	lockdown_any_partnered_father_de ///
	lockdown_any_partnered_mother_de ///
	lockdown_any_solo_father_depchil ///
	lockdown_any_solo_mother_depchil ///
	lockdown_any_youngest_child_ageb ///
	v175 ///
	lockdown_any_youngest_child_aget ///
	lockdown_any_youngest_child_agep ///
	lockdown_any_youngest_child_agei ///
	lockdown_any_youngest_child_agec ///
	any_benefit_receipt_partnered_fa ///
	any_benefit_receipt_partnered_mo ///
	any_benefit_receipt_solo_father_ ///
	any_benefit_receipt_solo_mother_ ///
	, re
	
	

xtlogit enough_income ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	pwb_qhealthexcellentpoorvery_goo ///
	pwb_qhealthexcellentpoorgood ///
	pwb_qhealthexcellentpoorfair ///
	pwb_qhealthexcellentpoorpoor ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	pwb_qtimelonelya_little_of_the_t ///
	pwb_qtimelonelysome_of_the_time ///
	pwb_qtimelonelymost_of_the_time ///
	pwb_qtimelonelyall_of_the_time ///
	hcq_qdampormouldminor_problem ///
	hcq_qdampormouldmajor_problem ///
	hcq_qkeepingwarmminor_problem ///
	hcq_qkeepingwarmmajor_problem ///
	any_benefit_receipt_winter_energ ///
	etheuropean ///
	ethmaori ///
	ethpacific ///
	ethasian ///
	ethmelaa ///
	ethother ///
	partnered_father_depchild ///
	partnered_mother_depchild ///
	solo_father_depchild ///
	solo_mother_depchild ///
	other_father ///
	other_mother ///
	youngest_child_agebaby_fm_pkg ///
	youngest_child_agebaby_no_pkg ///
	youngest_child_agetodler ///
	youngest_child_ageprimary ///
	youngest_child_ageintermediate ///
	youngest_child_agecollege ///
	low_income ///
	earned_self_emp ///
	age_cat20_to_29 ///
	age_cat30_to_39 ///
	age_cat40_to_49 ///
	age_cat50_to_59 ///
	age_cat60_to_69 ///
	age_cat70_to_79 ///
	age_cat80_up ///
	dvsexmale ///
	dvregcouncilbay_of_plenty ///
	dvregcouncilcanterbury ///
	dvregcouncilgisborne ///
	dvregcouncilhawkes_bay ///
	dvregcouncilmanawatu_wanganui ///
	dvregcouncilmarlborough ///
	dvregcouncilnelson ///
	dvregcouncilnorthland ///
	dvregcouncilotago ///
	dvregcouncilsouthland ///
	dvregcounciltaranaki ///
	dvregcounciltasman ///
	dvregcouncilwaikato ///
	dvregcouncilwellington ///
	dvregcouncilwest_coast ///
	winter_energy_payment_partnered_ ///
	v166 ///
	winter_energy_payment_solo_fathe ///
	winter_energy_payment_solo_mothe ///
	winter_energy_payment_low_income ///
	lockdown_any_partnered_father_de ///
	lockdown_any_partnered_mother_de ///
	lockdown_any_solo_father_depchil ///
	lockdown_any_solo_mother_depchil ///
	lockdown_any_youngest_child_ageb ///
	v175 ///
	lockdown_any_youngest_child_aget ///
	lockdown_any_youngest_child_agep ///
	lockdown_any_youngest_child_agei ///
	lockdown_any_youngest_child_agec ///
	any_benefit_receipt_partnered_fa ///
	any_benefit_receipt_partnered_mo ///
	any_benefit_receipt_solo_father_ ///
	any_benefit_receipt_solo_mother_ ///
	, re
	
xtlogit no_damp_or_mould ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	mhs_qenoughincomeenough_money ///
	mhs_qenoughincomeonly_just_enoug ///
	mhs_qenoughincomenot_enough_mone ///
	pwb_qhealthexcellentpoorvery_goo ///
	pwb_qhealthexcellentpoorgood ///
	pwb_qhealthexcellentpoorfair ///
	pwb_qhealthexcellentpoorpoor ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	pwb_qtimelonelya_little_of_the_t ///
	pwb_qtimelonelysome_of_the_time ///
	pwb_qtimelonelymost_of_the_time ///
	pwb_qtimelonelyall_of_the_time ///
	hcq_qkeepingwarmminor_problem ///
	hcq_qkeepingwarmmajor_problem ///
	any_benefit_receipt_winter_energ ///
	etheuropean ///
	ethmaori ///
	ethpacific ///
	ethasian ///
	ethmelaa ///
	ethother ///
	partnered_father_depchild ///
	partnered_mother_depchild ///
	solo_father_depchild ///
	solo_mother_depchild ///
	other_father ///
	other_mother ///
	youngest_child_agebaby_fm_pkg ///
	youngest_child_agebaby_no_pkg ///
	youngest_child_agetodler ///
	youngest_child_ageprimary ///
	youngest_child_ageintermediate ///
	youngest_child_agecollege ///
	low_income ///
	earned_self_emp ///
	age_cat20_to_29 ///
	age_cat30_to_39 ///
	age_cat40_to_49 ///
	age_cat50_to_59 ///
	age_cat60_to_69 ///
	age_cat70_to_79 ///
	age_cat80_up ///
	dvsexmale ///
	dvregcouncilbay_of_plenty ///
	dvregcouncilcanterbury ///
	dvregcouncilgisborne ///
	dvregcouncilhawkes_bay ///
	dvregcouncilmanawatu_wanganui ///
	dvregcouncilmarlborough ///
	dvregcouncilnelson ///
	dvregcouncilnorthland ///
	dvregcouncilotago ///
	dvregcouncilsouthland ///
	dvregcounciltaranaki ///
	dvregcounciltasman ///
	dvregcouncilwaikato ///
	dvregcouncilwellington ///
	dvregcouncilwest_coast ///
	winter_energy_payment_partnered_ ///
	v166 ///
	winter_energy_payment_solo_fathe ///
	winter_energy_payment_solo_mothe ///
	winter_energy_payment_low_income ///
	lockdown_any_partnered_father_de ///
	lockdown_any_partnered_mother_de ///
	lockdown_any_solo_father_depchil ///
	lockdown_any_solo_mother_depchil ///
	lockdown_any_youngest_child_ageb ///
	v175 ///
	lockdown_any_youngest_child_aget ///
	lockdown_any_youngest_child_agep ///
	lockdown_any_youngest_child_agei ///
	lockdown_any_youngest_child_agec ///
	any_benefit_receipt_partnered_fa ///
	any_benefit_receipt_partnered_mo ///
	any_benefit_receipt_solo_father_ ///
	any_benefit_receipt_solo_mother_ ///
	, re
	
	
	
	
xtlogit warm_home ///
	wavenov20 ///
	wavefeb21 ///
	wavemay21 ///
	lockdown_any ///
	pwb_qtrustmostpeoplescale ///
	dep17 ///
	mhs_qenoughincomeenough_money ///
	mhs_qenoughincomeonly_just_enoug ///
	mhs_qenoughincomenot_enough_mone ///
	pwb_qhealthexcellentpoorvery_goo ///
	pwb_qhealthexcellentpoorgood ///
	pwb_qhealthexcellentpoorfair ///
	pwb_qhealthexcellentpoorpoor ///
	dvlfsnot_in_labour_force ///
	dvlfsunemployed ///
	numjobsmulti_job ///
	pwb_qdiscriminated ///
	pwb_qtimelonelya_little_of_the_t ///
	pwb_qtimelonelysome_of_the_time ///
	pwb_qtimelonelymost_of_the_time ///
	pwb_qtimelonelyall_of_the_time ///
	hcq_qdampormouldminor_problem ///
	hcq_qdampormouldmajor_problem ///
	any_benefit_receipt_winter_energ ///
	etheuropean ///
	ethmaori ///
	ethpacific ///
	ethasian ///
	ethmelaa ///
	ethother ///
	partnered_father_depchild ///
	partnered_mother_depchild ///
	solo_father_depchild ///
	solo_mother_depchild ///
	other_father ///
	other_mother ///
	youngest_child_agebaby_fm_pkg ///
	youngest_child_agebaby_no_pkg ///
	youngest_child_agetodler ///
	youngest_child_ageprimary ///
	youngest_child_ageintermediate ///
	youngest_child_agecollege ///
	low_income ///
	earned_self_emp ///
	age_cat20_to_29 ///
	age_cat30_to_39 ///
	age_cat40_to_49 ///
	age_cat50_to_59 ///
	age_cat60_to_69 ///
	age_cat70_to_79 ///
	age_cat80_up ///
	dvsexmale ///
	dvregcouncilbay_of_plenty ///
	dvregcouncilcanterbury ///
	dvregcouncilgisborne ///
	dvregcouncilhawkes_bay ///
	dvregcouncilmanawatu_wanganui ///
	dvregcouncilmarlborough ///
	dvregcouncilnelson ///
	dvregcouncilnorthland ///
	dvregcouncilotago ///
	dvregcouncilsouthland ///
	dvregcounciltaranaki ///
	dvregcounciltasman ///
	dvregcouncilwaikato ///
	dvregcouncilwellington ///
	dvregcouncilwest_coast ///
	winter_energy_payment_partnered_ ///
	v166 ///
	winter_energy_payment_solo_fathe ///
	winter_energy_payment_solo_mothe ///
	winter_energy_payment_low_income ///
	lockdown_any_partnered_father_de ///
	lockdown_any_partnered_mother_de ///
	lockdown_any_solo_father_depchil ///
	lockdown_any_solo_mother_depchil ///
	lockdown_any_youngest_child_ageb ///
	v175 ///
	lockdown_any_youngest_child_aget ///
	lockdown_any_youngest_child_agep ///
	lockdown_any_youngest_child_agei ///
	lockdown_any_youngest_child_agec ///
	any_benefit_receipt_partnered_fa ///
	any_benefit_receipt_partnered_mo ///
	any_benefit_receipt_solo_father_ ///
	any_benefit_receipt_solo_mother_ ///
	, re
